const noTaskQuotes = [
    "Enjoy the calm.",
    "Take a break.",
    "Relax and recharge.",
    "Breathe easy.",
    "Time to unwind.",
    "Savor the moment.",
    "Embrace the quiet.",
    "Find your peace.",
    "Reflect and rest.",
    "Pause and breathe.",
    "Cherish the stillness.",
    "Enjoy the silence.",
    "Take it easy.",
    "Rest and relax.",
    "Unwind and enjoy.",
    "Calm your mind.",
    "Find tranquility.",
    "Enjoy the downtime.",
    "Take a moment for yourself.",
    "Relax your mind and body.",
    "Enjoy the peace and quiet.",
    "Take a breather and relax.",
    "Find your calm and center.",
    "Enjoy the serenity around you.",
    "Take a pause and reflect.",
    "Relax and enjoy the moment.",
    "Find your zen and peace.",
    "Enjoy the quiet and stillness.",
    "Take it slow and easy.",
    "Rest and reflect on life.",
    "Enjoy the stillness and calm.",
    "Take a rest and recharge.",
    "Relax and breathe deeply.",
    "Find your peace and tranquility.",
    "Enjoy the calm and quiet.",
    "Take a moment to unwind.",
    "Relax and unwind completely.",
    "Find tranquility and peace.",
    "Enjoy the downtime fully.",
    "Take a break and relax.",
    "Relax your mind and soul.",
    "Enjoy the peace and calm.",
    "Take a breather and enjoy.",
    "Find your calm and peace.",
    "Enjoy the serenity fully.",
    "Take a pause and breathe.",
    "Relax and enjoy the quiet.",
    "Find your zen and calm.",
    "Enjoy the quiet moments.",
    "Take it slow and relax.",
    "Rest and reflect deeply.",
    "Enjoy the stillness fully.",
    "Take a rest and relax.",
    "Relax and breathe deeply.",
    "Find your peace and calm.",
    "Enjoy the calm moments.",
    "Take a moment to relax.",
    "Relax and unwind fully.",
    "Find tranquility and calm.",
    "Enjoy the downtime moments.",
    "Take a break and breathe.",
    "Relax your mind fully.",
    "Enjoy the peace moments.",
    "Take a breather and rest.",
    "Find your calm moments.",
    "Enjoy the serenity moments.",
    "Take a pause and relax.",
    "Relax and enjoy fully.",
    "Find your zen moments.",
    "Enjoy the quiet fully.",
    "Take it slow and breathe.",
    "Rest and reflect fully.",
    "Enjoy the stillness moments.",
    "Take a rest and breathe.",
    "Relax and breathe fully.",
    "Find your peace moments."
];

const withTaskQuotes = [
    "Stay focused.",
    "Keep pushing.",
    "You got this.",
    "Stay on track.",
    "Keep moving.",
    "Stay determined.",
    "Keep going.",
    "Stay motivated.",
    "Keep striving.",
    "Stay productive.",
    "Keep working.",
    "Stay committed.",
    "Keep hustling.",
    "Stay driven.",
    "Keep achieving.",
    "Stay dedicated.",
    "Keep progressing.",
    "Stay on task.",
    "Keep advancing.",
    "Stay engaged.",
    "Keep grinding.",
    "Stay persistent.",
    "Keep at it.",
    "Stay focused and determined.",
    "Keep pushing forward.",
    "You got this, keep going.",
    "Stay on track and focused.",
    "Keep moving forward.",
    "Stay determined and strong.",
    "Keep going, you got this.",
    "Stay motivated and driven.",
    "Keep striving for success.",
    "Stay productive and focused.",
    "Keep working hard.",
    "Stay committed to your goals.",
    "Keep hustling and grinding.",
    "Stay driven and focused.",
    "Keep achieving your dreams.",
    "Stay dedicated and committed.",
    "Keep progressing forward.",
    "Stay on task and focused.",
    "Keep advancing towards goals.",
    "Stay engaged and motivated.",
    "Keep grinding and pushing.",
    "Stay persistent and strong.",
    "Keep at it, don't stop.",
    "Stay focused and strong.",
    "Keep pushing through challenges.",
    "You got this, stay strong.",
    "Stay on track and motivated.",
    "Keep moving towards goals.",
    "Stay determined and focused.",
    "Keep going, don't give up.",
    "Stay motivated and persistent.",
    "Keep striving for greatness.",
    "Stay productive and driven.",
    "Keep working towards success.",
    "Stay committed and focused.",
    "Keep hustling and achieving.",
    "Stay driven and motivated.",
    "Keep achieving your goals.",
    "Stay dedicated and strong.",
    "Keep progressing and moving.",
    "Stay on task and driven.",
    "Keep advancing and achieving.",
    "Stay engaged and focused.",
    "Keep grinding and achieving.",
    "Stay persistent and motivated.",
    "Keep at it, stay strong.",
    "Stay focused and driven.",
    "Keep pushing towards success.",
    "You got this, keep striving.",
    "Stay on track and driven.",
    "Keep moving and achieving.",
    "Stay determined and motivated.",
    "Keep going, stay strong.",
    "Stay motivated and achieving.",
    "Keep striving and pushing.",
    "Stay productive and achieving.",
    "Keep working and progressing.",
    "Stay committed and driven.",
    "Keep hustling and progressing.",
    "Stay driven and achieving.",
    "Keep achieving and striving.",
    "Stay dedicated and achieving.",
    "Keep progressing and striving.",
    "Stay on task and achieving.",
    "Keep advancing and striving.",
    "Stay engaged and achieving.",
    "Keep grinding and striving.",
    "Stay persistent and achieving.",
    "Keep at it, stay driven."
];

module.exports = { noTaskQuotes, withTaskQuotes };